steps:
  # Inital infrastructure setup
  - name: "gcr.io/cloudbuilders/gcloud"
    id: Inital infra setup
    args:
      - '-c'
      - |
        gsutil mb gs://${PROJECT_ID}-bank-of-anthos-tf-state
        sed -i "s/bucket = \"bank-of-anthos-tf-state\"/bucket = \"${PROJECT_ID}-bank-of-anthos-tf-state\"/" main.tf
        cd infra-intial-setup
        terraform init
        terraform plan --var project_id=${PROJECT_ID}
        terraform apply --var project_id=${PROJECT_ID} -auto-approve


  - name: "gcr.io/cloudbuilders/gcloud"
    id: GKE infra setup
    args:
      - '-c'
      - |
        gsutil mb gs://${PROJECT_ID}-bank-of-anthos-tf-state
        sed -i "s/bucket = \"bank-of-anthos-tf-state\"/bucket = \"${PROJECT_ID}-bank-of-anthos-tf-state\"/" main.tf
        cd gke-setup
        terraform init
        terraform plan --var project_id=${PROJECT_ID}
        terraform apply --var project_id=${PROJECT_ID} -auto-approve

options:
  dynamic_substitutions: true
  logging: CLOUD_LOGGING_ONLY
