---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bank-of-anthos
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Pruthvi2340/bank-of-anthos-gcp-k8s-manifest-repo.git
    targetRevision: HEAD
    path: bank-of-anthos-gcp-k8s-manifest-repo/kubernetes-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: bank-of-anthos
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true