######################################################################
# Setup up the FrontendConfig resource that enables HTTP -> HTTPS
# redirection in at the Ingress Loadbalancer
######################################################################
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: boa-frontend-config
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
