apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: bank-ssl-certificate
spec:
  domains:
    - bank-of-anthos.xyz  # repace me with DNS name mapped to bank-address
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: bank-address # create me with `gcloud compute addresses create bank-address --global`
    networking.gke.io/managed-certificates: bank-ssl-certificate
    kubernetes.io/ingress.allow-http: "false"
spec:
  backend:
    serviceName: frontend-nodeport
    servicePort: 8080