---
apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-config
data:
  LOCAL_ROUTING_NUM: "883745000"
  PUB_KEY_PATH: "/tmp/.ssh/publickey"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-api-config
data:
  TRANSACTIONS_API_ADDR: "ledgerwriter:8080"
  BALANCES_API_ADDR: "balancereader:8080"
  HISTORY_API_ADDR: "transactionhistory:8080"
  CONTACTS_API_ADDR: "contacts:8080"
  USERSERVICE_API_ADDR: "userservice:8080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-data-config
data:
  USE_DEMO_DATA: "True"
  DEMO_LOGIN_USERNAME: "testuser"
  # All demo user accounts are hardcoded to use the login password 'bankofanthos'
  DEMO_LOGIN_PASSWORD: "bankofanthos"
---
apiVersion: v1
kind: Secret
metadata:
  name: accounts-db-config
  labels:
    app: accounts-db
stringData:
  POSTGRES_DB: accounts-db
  POSTGRES_USER: accounts-admin
  POSTGRES_PASSWORD: accounts-pwd
  ACCOUNTS_DB_URI: postgresql://accounts-admin:accounts-pwd@accounts-db-pgpool:5432/accounts-db
---
apiVersion: v1
kind: Secret
metadata:
  name: ledger-db-config
  labels:
    app: ledger-db
stringData:
  POSTGRES_DB: accounts-db
  POSTGRES_USER: accounts-admin
  POSTGRES_PASSWORD: accounts-pwd
  SPRING_DATASOURCE_URL: jdbc:postgresql://accounts-db-pgpool:5432/accounts-db
  SPRING_DATASOURCE_USERNAME: accounts-admin # should match POSTGRES_USER
  SPRING_DATASOURCE_PASSWORD: accounts-pwd # should match POSTGRES_PASSWORD
